MAP_CONFIG = "$1";
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"resourcemanager/resourcemanager.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/modules/socket/socket.js",
	"libs/modules/particle/particle.js",
	"promise/bin/promise.js",
	"bin-debug/core/datas/const.js",
	"bin-debug/core/datas/model.js",
	"bin-debug/core/view/BaseScene.js",
	"bin-debug/core/datas/Config.js",
	"bin-debug/core/view/BaseLayer.js",
	"bin-debug/core/view/game/base/GameSceneBase.js",
	"bin-debug/core/view/game/robot/LogicBase.js",
	"bin-debug/core/view/game/brnn/GameScene.js",
	"bin-debug/core/view/game/majiang/GameScene.js",
	"bin-debug/core/view/game/base/AnimationBase.js",
	"bin-debug/core/view/game/base/CardBase.js",
	"bin-debug/core/view/game/base/DiscardBoxBase.js",
	"bin-debug/core/view/game/base/GameDatasBase.js",
	"bin-debug/core/view/game/base/GameEffectLayerBase.js",
	"bin-debug/core/view/game/base/GameMsgHandlerBase.js",
	"bin-debug/core/net/NetConst.js",
	"bin-debug/core/view/game/base/GameUIBase.js",
	"bin-debug/core/view/game/base/PlayerBase.js",
	"bin-debug/core/view/game/base/RoundAccountLayerBase.js",
	"bin-debug/core/control/platform/H5WebBase.js",
	"bin-debug/core/view/game/brnn/Zoom.js",
	"bin-debug/core/view/game/ddz/GameScene.js",
	"bin-debug/core/view/game/majiang/cardbox/CardBox.js",
	"bin-debug/core/view/game/majiang/DiscardBox.js",
	"bin-debug/core/view/game/niuniu/GameScene.js",
	"bin-debug/core/view/game/niuniu/HandCardBox.js",
	"bin-debug/core/control/platform/IPlatform.js",
	"bin-debug/core/view/game/robot/zjh/ZJHLogic.js",
	"bin-debug/core/view/game/zjh/GameScene.js",
	"bin-debug/core/view/Layers/create/RoomConfigLayerBase.js",
	"bin-debug/core/view/SelectScene/SelectScene.js",
	"bin-debug/core/view/skins/CommonBtn.js",
	"bin-debug/core/view/skins/CountDown.js",
	"bin-debug/core/view/skins/RadioBtn.js",
	"bin-debug/DebugUsers.js",
	"bin-debug/LoginScene.js",
	"bin-debug/utils/GzqdSdk.js",
	"bin-debug/utils/IWebView.js",
	"bin-debug/core/view/effect/Effect.js",
	"bin-debug/core/view/game/animation/Lost.js",
	"bin-debug/core/view/game/animation/Start.js",
	"bin-debug/core/view/game/animation/Win.js",
	"bin-debug/core/view/game/base/Animation.js",
	"bin-debug/core/control/platform/NativeBridge.js",
	"bin-debug/core/view/game/base/AnimationMjZhongMa.js",
	"bin-debug/core/view/game/base/Bubble.js",
	"bin-debug/core/control/platform/NativePlatform.js",
	"bin-debug/core/view/game/base/ChatBox.js",
	"bin-debug/core/view/game/base/ChatTalkBox.js",
	"bin-debug/core/control/platform/PayCode.js",
	"bin-debug/core/control/pool/Distributor.js",
	"bin-debug/core/control/pool/IDistributor.js",
	"bin-debug/core/view/game/base/GameEvent.js",
	"bin-debug/core/control/pool/IPoolObject.js",
	"bin-debug/core/control/pool/ObjectGenerator.js",
	"bin-debug/core/control/ResManager.js",
	"bin-debug/core/control/SceneManager.js",
	"bin-debug/core/control/SelectSceneMsgHandler.js",
	"bin-debug/core/view/game/brnn/ani/chipsPoolNiuNiu.js",
	"bin-debug/core/view/game/brnn/ani/chipsPoolShanguang.js",
	"bin-debug/core/view/game/brnn/ani/ZhuanJiaShanguang.js",
	"bin-debug/core/view/game/brnn/BrnnCountDown.js",
	"bin-debug/core/view/game/brnn/BrnnRadioBtn.js",
	"bin-debug/core/view/game/brnn/BrnnZoom.js",
	"bin-debug/core/view/game/brnn/ChipsPool.js",
	"bin-debug/core/view/game/brnn/DisCardBox.js",
	"bin-debug/core/view/game/brnn/GameDatas.js",
	"bin-debug/core/view/game/brnn/GameLang.js",
	"bin-debug/core/view/game/brnn/GameListLayer.js",
	"bin-debug/core/view/game/brnn/GameMsgHandler.js",
	"bin-debug/core/control/SoundManage.js",
	"bin-debug/core/view/game/brnn/GameUI.js",
	"bin-debug/core/view/game/brnn/HandCardBoxBr.js",
	"bin-debug/core/view/game/brnn/HistroyBox.js",
	"bin-debug/core/view/game/brnn/model.js",
	"bin-debug/core/view/game/brnn/Player.js",
	"bin-debug/core/view/game/brnn/ShenQingListLayer.js",
	"bin-debug/core/view/game/brnn/TipBar.js",
	"bin-debug/core/view/game/brnn/WangListLayer.js",
	"bin-debug/core/view/game/brnn/WinLose.js",
	"bin-debug/core/view/game/brnn/ZhuanJiaCuoPai.js",
	"bin-debug/core/control/GlobalMsgHandler.js",
	"bin-debug/core/view/game/ddz/Card.js",
	"bin-debug/core/view/game/ddz/CardBox.js",
	"bin-debug/core/view/game/ddz/dh/liandui.js",
	"bin-debug/core/view/game/ddz/dh/plane.js",
	"bin-debug/core/view/game/ddz/dh/RedLight.js",
	"bin-debug/core/view/game/ddz/dh/shunzi.js",
	"bin-debug/core/view/game/ddz/dh/wangzha.js",
	"bin-debug/core/view/game/ddz/dh/zhadan.js",
	"bin-debug/core/view/game/ddz/DiscardBox.js",
	"bin-debug/core/view/game/ddz/GameBtnBar.js",
	"bin-debug/core/view/game/ddz/GameDatas.js",
	"bin-debug/core/view/game/ddz/GameEffectLayer.js",
	"bin-debug/core/view/game/ddz/GameMsgHandler.js",
	"bin-debug/core/datas/ConfigDef.js",
	"bin-debug/core/view/game/ddz/GameUI.js",
	"bin-debug/core/view/game/ddz/logic/HandCard.js",
	"bin-debug/core/view/game/ddz/logic/Poker.js",
	"bin-debug/core/view/game/ddz/logic/PokerCard.js",
	"bin-debug/core/view/game/ddz/model.js",
	"bin-debug/core/view/game/ddz/Player.js",
	"bin-debug/core/view/game/ddz/RoundAccountDdzLyayer.js",
	"bin-debug/core/view/game/DissolveLayer.js",
	"bin-debug/core/view/game/GameConst.js",
	"bin-debug/core/view/game/majiang/Aui/majiangchiAui.js",
	"bin-debug/core/view/game/majiang/Aui/majiangGangAui.js",
	"bin-debug/core/view/game/majiang/Aui/majianghuAui.js",
	"bin-debug/core/view/game/majiang/Aui/majiangpengAui.js",
	"bin-debug/core/view/game/majiang/Aui/majiangshaoAui.js",
	"bin-debug/core/view/game/majiang/Aui/majiangtanAui.js",
	"bin-debug/core/view/game/majiang/Card.js",
	"bin-debug/core/control/LayerManage.js",
	"bin-debug/core/view/game/majiang/cardbox/CardBoxLeft.js",
	"bin-debug/core/view/game/majiang/cardbox/CardBoxRight.js",
	"bin-debug/core/view/game/majiang/cardbox/CardBoxTop.js",
	"bin-debug/core/view/game/majiang/cardbox/CardType.js",
	"bin-debug/core/datas/Filters.js",
	"bin-debug/core/view/game/majiang/GameBtnBar.js",
	"bin-debug/core/view/game/majiang/GameConst.js",
	"bin-debug/core/view/game/majiang/GameDatas.js",
	"bin-debug/core/view/game/majiang/GameEffectLayer.js",
	"bin-debug/core/view/game/majiang/GameMsgHandler.js",
	"bin-debug/core/control/ConfigDefManager.js",
	"bin-debug/core/view/game/majiang/GameUI.js",
	"bin-debug/core/view/game/majiang/logic/Majiang.js",
	"bin-debug/core/view/game/majiang/logic/MajiangCard.js",
	"bin-debug/core/view/game/majiang/model.js",
	"bin-debug/core/view/game/majiang/Player.js",
	"bin-debug/core/view/game/majiang/RoundAccountMjLyayer.js",
	"bin-debug/core/view/game/majiang/SelectBox.js",
	"bin-debug/core/view/game/majiang/SelectBtn.js",
	"bin-debug/core/view/game/majiang/TanDiscardBox.js",
	"bin-debug/core/view/game/majiang/TimeBox.js",
	"bin-debug/core/view/game/niuniu/CalBox.js",
	"bin-debug/core/view/game/niuniu/Card.js",
	"bin-debug/core/view/game/niuniu/CuoPaiAni.js",
	"bin-debug/core/view/game/niuniu/DiscardBox.js",
	"bin-debug/core/view/game/niuniu/GameBtnBar.js",
	"bin-debug/core/view/game/niuniu/GameDatas.js",
	"bin-debug/core/view/game/niuniu/GameEffectLayer.js",
	"bin-debug/core/view/game/niuniu/GameMsgHandler.js",
	"bin-debug/core/datas/GameLangs.js",
	"bin-debug/core/view/game/niuniu/GameUI.js",
	"bin-debug/core/datas/LocalDatas.js",
	"bin-debug/core/view/game/niuniu/Player.js",
	"bin-debug/core/view/game/niuniu/RoundAccountLayer.js",
	"bin-debug/core/view/game/PhoneInfoBox.js",
	"bin-debug/AssetAdapter.js",
	"bin-debug/core/view/game/robot/niuniu/NiuniuLogic.js",
	"bin-debug/core/view/game/robot/niuniu/Poker.js",
	"bin-debug/core/view/game/robot/Robot.js",
	"bin-debug/core/view/game/robot/SelectSceneLogic.js",
	"bin-debug/core/view/game/robot/zjh/ZJHGoldLogic.js",
	"bin-debug/core/net/BaseMsgHandler.js",
	"bin-debug/core/view/game/zjh/Card.js",
	"bin-debug/core/view/game/zjh/ChipsBar.js",
	"bin-debug/core/view/game/zjh/ChipsObj.js",
	"bin-debug/core/view/game/zjh/ChipsPool.js",
	"bin-debug/core/view/game/zjh/CuoPaiAni.js",
	"bin-debug/core/view/game/zjh/DiscardBox.js",
	"bin-debug/core/view/game/zjh/GameBtnBar.js",
	"bin-debug/core/view/game/zjh/GameDatas.js",
	"bin-debug/core/view/game/zjh/GameEffectLayer.js",
	"bin-debug/core/view/game/zjh/GameLangs.js",
	"bin-debug/core/view/game/zjh/GameMsgHandler.js",
	"bin-debug/core/net/DataView.js",
	"bin-debug/core/view/game/zjh/GameUI.js",
	"bin-debug/core/view/game/zjh/model.js",
	"bin-debug/core/view/game/zjh/PkAniLayer.js",
	"bin-debug/core/view/game/zjh/Player.js",
	"bin-debug/core/view/Layers/AccountLayer.js",
	"bin-debug/core/view/Layers/AppDownload.js",
	"bin-debug/core/view/Layers/BindingPhoneLayer.js",
	"bin-debug/core/view/Layers/create/CreateRoomLayer.js",
	"bin-debug/core/view/Layers/create/Dezhou.RoomConfigLayerSkin.js",
	"bin-debug/core/view/Layers/create/DZZRoomConfigLayer.js",
	"bin-debug/core/view/Layers/create/MaJiangRoomConfigLayer.js",
	"bin-debug/core/view/Layers/create/NiuniuRoomcConfigLayer.js",
	"bin-debug/core/net/GameLang.js",
	"bin-debug/core/view/Layers/create/SZPRoomConfigLayer.js",
	"bin-debug/core/view/Layers/create/TwoNiuniuRoomcConfigLayer.js",
	"bin-debug/core/view/Layers/DrawLayer.js",
	"bin-debug/core/view/Layers/EnterRoomLayer.js",
	"bin-debug/core/view/Layers/GameAnnouncementLayer.js",
	"bin-debug/core/view/Layers/GameMessagetDetaiLayer.js",
	"bin-debug/core/view/Layers/GameMessgeListLayer.js",
	"bin-debug/core/view/Layers/HintSkinLayer.js",
	"bin-debug/core/view/Layers/ModifyUserInfoLayer.js",
	"bin-debug/core/view/Layers/PaiMaiLayer.js",
	"bin-debug/core/view/Layers/PaiMaiWindowLayer.js",
	"bin-debug/core/view/Layers/PerforManceLayer.js",
	"bin-debug/core/view/Layers/PlayMethodLayer.js",
	"bin-debug/core/view/Layers/PreforManceSecondLayer.js",
	"bin-debug/core/view/Layers/RankingListLayer.js",
	"bin-debug/core/view/Layers/recharge/FirstGiftLayer.js",
	"bin-debug/core/view/Layers/recharge/GetGiftAni.js",
	"bin-debug/core/view/Layers/recharge/RechargeLayer.js",
	"bin-debug/core/view/Layers/RulesLayer.js",
	"bin-debug/core/view/Layers/SafeBoxLayer.js",
	"bin-debug/core/view/Layers/SettingLayer.js",
	"bin-debug/core/view/Layers/ShareDayLayer.js",
	"bin-debug/core/view/Layers/ShareGift.js",
	"bin-debug/core/view/Layers/SharePost.js",
	"bin-debug/core/view/Layers/UserInfoLayer.js",
	"bin-debug/core/view/Layers/WaitingLayer.js",
	"bin-debug/core/view/Layers/WelfareCenterLayer.js",
	"bin-debug/core/view/SelectScene/HunderNNSelectRoomItem.js",
	"bin-debug/core/control/platform/H5WechatOAPlatform.js",
	"bin-debug/core/view/SelectScene/SpeakerMan.js",
	"bin-debug/core/net/NetEvent.js",
	"bin-debug/core/net/Protocols.js",
	"bin-debug/core/view/skins/Danmu.js",
	"bin-debug/core/view/skins/DropDownList.js",
	"bin-debug/core/view/skins/GrayBtn.js",
	"bin-debug/core/view/skins/HeadBox.js",
	"bin-debug/core/view/skins/LoadingIcon.js",
	"bin-debug/core/view/skins/ProgressBar.js",
	"bin-debug/core/net/NetManage.js",
	"bin-debug/core/view/skins/ToggleButton.js",
	"bin-debug/core/view/skins/Tween.js",
	"bin-debug/core/net/ReceiveMsg.js",
	"bin-debug/Global.js",
	"bin-debug/core/net/WebSocket.js",
	"bin-debug/Main.js",
	"bin-debug/test/TestLayer.js",
	"bin-debug/ThemeAdapter.js",
	"bin-debug/utils/Base64.js",
	"bin-debug/utils/BitmapLabel.js",
	"bin-debug/utils/CoolTime.js",
	"bin-debug/utils/Decorators.js",
	"bin-debug/utils/EffectUtils.js",
	"bin-debug/utils/EventManager.js",
	"bin-debug/utils/FrameManager.js",
	"bin-debug/core/control/platform/H5WechatPlatform.js",
	"bin-debug/utils/HtmlWebImgView.js",
	"bin-debug/utils/HtmlWebView.js",
	"bin-debug/core/control/EVENT_DEFINF.js",
	"bin-debug/utils/LogManage.js",
	"bin-debug/utils/NativeWebView.js",
	"bin-debug/utils/Recorder.js",
	"bin-debug/utils/SprintfWrapper.js",
	"bin-debug/utils/StringUtil.js",
	"bin-debug/utils/Toast.js",
	"bin-debug/utils/uploadPhoto.js",
	"bin-debug/utils/Util.js",
	"bin-debug/utils/WoPlaySdk.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "fixedNarrow",
		contentWidth: 1136,
		contentHeight: 640,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};